site_name: RNC

nav:
    - 主页: index.md
    - 四年计划: four-year-plan.md
    - 课程教材: course-material.md
    - 链接导航: url-nav.md
    - AI加持的学习: acamedic-ai.md
    - 移动校园卡: campus-card.md
    - 必备软件: software-collection.md
theme:
  name: material
  language: zh
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
