site_name: RNC

nav:
    - 主页: index.md
    - 四年计划: four-year-plan.md
    - 课程教材: course-material.md
    - 链接导航: url-nav.md
    - 人工智能: acamedic-ai.md
    - 移动宽带: campus-card.md
    - 必备软件: software-collection.md
    - 常见问题: common-problem.md
    - 关于我们: about-us.md
theme:
  name: material
  language: zh
  icon: 
    logo: material/navigation-variant-outline
    icon: material/navigation-variant-outline
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
  custom_dir: overrides


markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg

