site_name: My Docs

theme:
  name: material
  language: zh
  palette:
    primary: indigo
    scheme: 
      - default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      - slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

theme:
  name: material
  language: zh
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
