site_name: RNC

nav:
    - 主页: index.md
    - 四年计划: four-year-plan.md

theme:
  name: material
  language: zh
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
